name: Global Stock Alert System

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Manual trigger support

jobs:
  stock-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance requests

      - name: Run Global Stock Alert Script
        env:
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        run: python global_stock_alert.py
