name: Stock Alert System

on:
  schedule:
    # Runs every 5 minutes during Indian market hours (9:30 AM - 3:30 PM IST, which is 4:00 AM - 10:00 AM UTC)
    - cron: "*/5 4-10 * * 1-5"  # Every 5 minutes, Monday to Friday
  workflow_dispatch:  # Allows manual trigger anytime

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pushbullet.py  # Install the pushbullet library
        pip install yfinance pandas  # Install necessary libraries
        pip install ta-lib requests holidays pytz  # Install additional libraries

    - name: Run Stock Alert Script
      env:
        PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}  # Make sure your Pushbullet API key is stored in GitHub Secrets
      run: python stock_alert.py
