name: Stock Alert System

on:
  schedule:
    # Runs every 5 minutes during Indian market hours (9:30 AM - 3:30 PM IST, which is 4:00 AM - 10:00 AM UTC)
   - cron: "*/5 3-9 * * 1-5"  # Every 5 minutes, Monday to Friday

  workflow_dispatch:  # Allows manual trigger anytime

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pushbullet.py  # Pushbullet for notifications
        pip install yfinance pandas numpy requests pytz  # Add all necessary libraries
        pip install holidays # Include additional optional dependencies

    - name: Run Stock Alert Script
      env:
        PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}  # Securely load API key from GitHub Secrets
      run: python stock_alert.py
