name: Stock Alert System

on:
  schedule:
    # Runs every 5 minutes during Indian market hours (9:15 AM - 3:30 PM IST)
    - cron: "*/5 3-9 * * 1-5"
  workflow_dispatch:

jobs:
  stock-alert:
    runs-on: ubuntu-latest
    
    env:
      UPSTOX_API_KEY: ${{ secrets.UPSTOX_API_KEY }}
      UPSTOX_API_SECRET: ${{ secrets.UPSTOX_API_SECRET }}
      PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Directories
      run: |
        mkdir -p logs

    - name: Validate Environment
      run: |
        python - <<EOF
        import os
        import sys
        
        required_vars = ['UPSTOX_API_KEY', 'UPSTOX_API_SECRET', 'PUSHBULLET_API_KEY']
        missing_vars = [var for var in required_vars if not os.getenv(var)]
        
        if missing_vars:
            print(f"Missing required environment variables: {', '.join(missing_vars)}")
            sys.exit(1)
        
        print("Environment validation successful")
        EOF

    - name: Run Stock Alert Script
      run: |
        # Add execution time to logs
        echo "Execution started at $(date)" >> logs/trading_bot.log
        python trading_bot.py
        echo "Execution completed at $(date)" >> logs/trading_bot.log

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs-${{ github.run_id }}
        path: logs/
        retention-days: 7

    - name: Send Status Notification
      if: always()
      run: |
        status="${{ job.status }}"
        message="Trading Bot Status Update\n\n"
        
        if [ "$status" = "success" ]; then
          message+="✅ Trading bot executed successfully"
        else
          message+="⚠️ Trading bot execution failed"
        fi
        
        message+="\nTime: $(date)"
        message+="\nRun ID: ${{ github.run_id }}"
        
        curl -X POST \
          --header 'Access-Token: ${{ secrets.PUSHBULLET_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --data-binary "{\"type\": \"note\", \"title\": \"Trading Bot Status\", \"body\": \"$message\"}" \
          https://api.pushbullet.com/v2/pushes
